import type { GlobalConfig } from 'payload'
import { portfolioAfterChange } from '../app/(frontend)/lib/portfolio/hooks'

export const Footer: GlobalConfig = {
  slug: 'footer',
  hooks: {
    afterChange: [portfolioAfterChange],
  },
  label: 'Footer',
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'socialLinks',
      type: 'array',
      fields: [
        {
          name: 'platform',
          type: 'select',
          required: true,
          options: [
            { label: 'Facebook', value: 'facebook' },
            { label: 'X (Twitter)', value: 'twitter' },
            { label: 'Instagram', value: 'instagram' },
            { label: 'LinkedIn', value: 'linkedin' },
            { label: 'GitHub', value: 'github' },
            { label: 'WhatsApp', value: 'whatsapp' },
          ],
          admin: { description: 'Select the social media platform for the link.' },
        },
        { name: 'url', type: 'text', required: true, admin: { description: 'The URL for the social media link.' } },
        {
          name: 'iconName',
          type: 'select',
          required: true,
          options: ['faFacebookF', 'faXTwitter', 'faInstagram', 'faLinkedin', 'faGithub', 'faWhatsapp', 'faWhatsappc', 'faGem', 'faHome', 'faEnvelope', 'faPhoneFlip'],
          admin: { description: 'The icon to display for the social media link.' },
        },
        { name: 'ariaLabel', type: 'text', required: true, admin: { description: 'The ARIA label for the social media link.' } },
      ],
    },
    {
      name: 'roles',
      type: 'group',
      label: 'Roles',
      fields: [
        { name: 'fullName', type: 'text', required: true },
        {
          name: 'footerRoles',
          type: 'text',
          hasMany: true,
          admin: { description: 'Short role list shown in the footer.' },
        }
      ],
    },
    {
      name: 'profiles',
      label: 'Freelance / Marketplace Profiles',
      type: 'array',
      fields: [
        { name: 'name', type: 'text', required: true, admin: { description: 'The name of the freelance or marketplace profile.' } },
        { name: 'url', type: 'text', required: true, admin: { description: 'The URL for the freelance or marketplace profile.' } },
      ],
    },
    {
      name: 'contactInfo',
      type: 'array',
      fields: [
        {
          name: 'type',
          type: 'select',
          required: true,
          options: [
            { label: 'Address', value: 'address' },
            { label: 'Email', value: 'email' },
            { label: 'Phone', value: 'phone' },
            { label: 'WhatsApp', value: 'whatsapp' },
          ],
          admin: { description: 'Select the type of contact info item.' },
        },
        {
          name: 'iconName',
          type: 'select',
          required: true,
          options: ['faFacebookF', 'faXTwitter', 'faInstagram', 'faLinkedin', 'faGithub', 'faWhatsapp', 'faWhatsappc', 'faGem', 'faHome', 'faEnvelope', 'faPhoneFlip'],
          admin: { description: 'The icon to display for the contact info item.' },
        },
        { name: 'content', type: 'text', required: true, admin: { description: 'The content for the contact info item.' } },
        { name: 'isLink', type: 'checkbox', admin: { description: 'Check if this contact info item is a link.' } },

        { name: 'url', type: 'text', admin: { description: 'The URL for the contact info item.' } },
        {
          name: 'className',
          type: 'select',
          defaultValue: 'text-white',
          options: ['text-white', 'text-primary', 'text-secondary', 'text-success', 'text-info', 'text-warning', 'text-danger'],
          admin: { description: 'Bootstrap text color class for the contact info item.' },
        },
      ],
    },
    {
      name: 'hiringCta',
      type: 'group',
      label: 'Hiring call-to-action',
      fields: [
        { name: 'label', type: 'text', admin: { description: 'The label for the hiring call-to-action.' } },
        { name: 'url', type: 'text', admin: { description: 'The URL for the hiring call-to-action.' } },
      ],
    },
    {
      name: 'copyRight',
      type: 'group',
      label: 'Copyright',
      fields: [
        { name: 'year', type: 'number', required: true, min: 0, admin: { description: 'The year is generated by the frontend.' } },
        {
          name: 'website',
          type: 'text',
          admin: { description: 'Used in the copyright line, e.g. eTarikhi.com. The year is generated by the frontend.' },
        },
        { name: 'url', type: 'text', required: true, admin: { description: 'Used in the copyright line, e.g. https://vTarikhi.com. The year is generated by the frontend.' } },
      ],
    },
  ],
}
