/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    about: About;
    header: Header;
    articles: Article;
    certificates: Certificate;
    educations: Education;
    experiences: Experience;
    projects: Project;
    services: Service;
    skills: Skill;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    educations: EducationsSelect<false> | EducationsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  experience: {
    years: number;
    title: string;
    description: string;
  };
  workPermit: {
    title: string;
    description: string;
  };
  uploadImages?: (number | Media)[] | null;
  images?:
    | {
        imageUrl: string;
        id?: string | null;
      }[]
    | null;
  interests: {
    title: string;
    description: string;
    areas?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  sureName: string;
  profileImage?: (number | null) | Media;
  imageUrl?: string | null;
  /**
   * Link behind the "Request CV" button.
   */
  requestCV?: string | null;
  /**
   * Job titles shown in the hero section.
   */
  professionTexts: string[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  excerpt: string;
  /**
   * URL key for /articles/{slug}. Made from the title when left empty. Keep it stable once the article is shared.
   */
  slug?: string | null;
  /**
   * Article body, as plain text. Separate paragraphs with a blank line. Leave empty and the article links out only (no page).
   */
  description?: string | null;
  /**
   * If checked, the article expert will be featured on the homepage.
   */
  featured?: boolean | null;
  category?: ('articles' | 'others') | null;
  publishedAt: string;
  /**
   * Minutes. Render as "{n} min" in the frontend.
   */
  readTime?: number | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  /**
   * Where the article is published (LinkedIn, Medium, ...).
   */
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  title: string;
  issuer: string;
  issuedAt: string;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  /**
   * Public credential URL.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations".
 */
export interface Education {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  title: string;
  institution: string;
  location?: string | null;
  /**
   * Display text, e.g. "2001 - 2007".
   */
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  title: string;
  date: string;
  company: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  title: string;
  /**
   * URL key for /projects/{slug}. Made from the title when left empty. Keep it stable once the project is shared.
   */
  slug?: string | null;
  /**
   * Used as the full image when the Image URL below is empty. It is also the thumbnail when the Place Holder Image URL is empty.
   */
  image?: (number | null) | Media;
  src?: string | null;
  placeHolder?: string | null;
  /**
   * Live site or case-study URL.
   */
  url?: string | null;
  /**
   * URL for the "Read More" link.
   */
  readMoreUrl?: string | null;
  categories: ('front-end' | 'back-end' | 'cms-crm')[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  category: string;
  /**
   * Icon shown next to the category. Only the icons the frontend has are listed.
   */
  iconFont?: ('faCode' | 'faCropAlt' | 'faLaptopCode' | 'faCodeBranch') | null;
  /**
   * One entry per bullet point.
   */
  descriptions: string[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  label: string;
  group: 'frontend' | 'backend';
  /**
   * Proficiency, 0-100.
   */
  value: number;
  /**
   * Bootstrap contextual color of the progress bar.
   */
  color: 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'about';
        value: number | About;
      } | null)
    | ({
        relationTo: 'header';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'educations';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  experience?:
    | T
    | {
        years?: T;
        title?: T;
        description?: T;
      };
  workPermit?:
    | T
    | {
        title?: T;
        description?: T;
      };
  uploadImages?: T;
  images?:
    | T
    | {
        imageUrl?: T;
        id?: T;
      };
  interests?:
    | T
    | {
        title?: T;
        description?: T;
        areas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  sureName?: T;
  profileImage?: T;
  imageUrl?: T;
  requestCV?: T;
  professionTexts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  slug?: T;
  description?: T;
  featured?: T;
  category?: T;
  publishedAt?: T;
  readTime?: T;
  image?: T;
  imageUrl?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  issuedAt?: T;
  image?: T;
  imageUrl?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations_select".
 */
export interface EducationsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  institution?: T;
  location?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  date?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  slug?: T;
  image?: T;
  src?: T;
  placeHolder?: T;
  url?: T;
  readMoreUrl?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  order?: T;
  category?: T;
  iconFont?: T;
  descriptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  order?: T;
  label?: T;
  group?: T;
  value?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  socialLinks?:
    | {
        /**
         * Select the social media platform for the link.
         */
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'github' | 'whatsapp';
        /**
         * The URL for the social media link.
         */
        url: string;
        /**
         * The icon to display for the social media link.
         */
        iconName:
          | 'faFacebookF'
          | 'faXTwitter'
          | 'faInstagram'
          | 'faLinkedin'
          | 'faGithub'
          | 'faWhatsapp'
          | 'faWhatsappc'
          | 'faGem'
          | 'faHome'
          | 'faEnvelope'
          | 'faPhoneFlip';
        /**
         * The ARIA label for the social media link.
         */
        ariaLabel: string;
        id?: string | null;
      }[]
    | null;
  roles: {
    fullName: string;
    /**
     * Short role list shown in the footer.
     */
    footerRoles?: string[] | null;
  };
  profiles?:
    | {
        /**
         * The name of the freelance or marketplace profile.
         */
        name: string;
        /**
         * The URL for the freelance or marketplace profile.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?:
    | {
        /**
         * Select the type of contact info item.
         */
        type: 'address' | 'email' | 'phone' | 'whatsapp';
        /**
         * The icon to display for the contact info item.
         */
        iconName:
          | 'faFacebookF'
          | 'faXTwitter'
          | 'faInstagram'
          | 'faLinkedin'
          | 'faGithub'
          | 'faWhatsapp'
          | 'faWhatsappc'
          | 'faGem'
          | 'faHome'
          | 'faEnvelope'
          | 'faPhoneFlip';
        /**
         * The content for the contact info item.
         */
        content: string;
        /**
         * Check if this contact info item is a link.
         */
        isLink?: boolean | null;
        /**
         * The URL for the contact info item.
         */
        url?: string | null;
        /**
         * Bootstrap text color class for the contact info item.
         */
        className?:
          | (
              | 'text-white'
              | 'text-primary'
              | 'text-secondary'
              | 'text-success'
              | 'text-info'
              | 'text-warning'
              | 'text-danger'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  hiringCta?: {
    /**
     * The label for the hiring call-to-action.
     */
    label?: string | null;
    /**
     * The URL for the hiring call-to-action.
     */
    url?: string | null;
  };
  copyRight: {
    /**
     * The year is generated by the frontend.
     */
    year: number;
    /**
     * Used in the copyright line, e.g. eTarikhi.com. The year is generated by the frontend.
     */
    website?: string | null;
    /**
     * Used in the copyright line, e.g. https://vTarikhi.com. The year is generated by the frontend.
     */
    url: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        iconName?: T;
        ariaLabel?: T;
        id?: T;
      };
  roles?:
    | T
    | {
        fullName?: T;
        footerRoles?: T;
      };
  profiles?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        type?: T;
        iconName?: T;
        content?: T;
        isLink?: T;
        url?: T;
        className?: T;
        id?: T;
      };
  hiringCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  copyRight?:
    | T
    | {
        year?: T;
        website?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}